# This pipeline triggers the existing infra and app Azure DevOps Pipelines
name: CI

# Commented so these don't run on every PR
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     types: [opened, reopened]
#     branches: 
#       - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        # The steps are successful if the pipeline has triggered not if the pipeline has succeeded
        # Therefore, it triggers them near simultaneously 
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/jakefawcett2298/Jake-Fawcett
            azure-pipeline-name: 'platform-tetris-infra'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/jakefawcett2298/Jake-Fawcett
            azure-pipeline-name: 'platform-tetris-app'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
